#语言 默认为简体中文
language: 'zh_cn'

#日志中日期格式
dateFormat: 'yyyy/MM/dd HH:mm:ss'

#行分隔符 Auto=自动，手动指定则填写如：'\r\n'
lineSeparator: 'Auto'

#即时保存 true为启用 false为禁用
#若启用则每条日志信息即时保存到文件，禁用则有一定缓冲区，但会在插件卸载时完整保存(若插件未正常卸载则存在部分记录丢失的可能)
realTimeSave: true

playerChat:
  #记录玩家聊天 true为启用 false为禁用
  enable: true
  #为每个玩家单独记录
  perPlayer: true

playerCommand:
  #记录玩家指令 true为启用 false为禁用
  enable: true
  #为每个玩家单独记录
  perPlayer: true
  #记录控制台指令 true为启用 false为禁用
  consoleCommand: true
  #记录op变更 true为启用 false为禁用
  #此项在记录玩家指令和记录控制台指令都启用的情况下才能完整生效
  opChange: true

playerGameModeChange:
  #记录玩家游戏模式变更 true为启用 false为禁用
  enable: true
  #为每个玩家单独记录
  perPlayer: false

#记录玩家加入/离开/被踢出
joinAndLeave: true

commandAlert:
  #非白名单OP执行命令警报 true为启用 false为禁用
  enable: true

  #玩家白名单 按示例格式添加
  whitelist:
    - player1
    - player2

  #命令白名单 按示例格式添加
  commandWhiteList:
    - /help
    - /suicide

  #非白名单命令取消执行 true为取消 false为不取消
  cancel: true

  handleMethod:
    #处理方法 0=不处理 1=发送全服公告 2=控制台执行命令 4=使该玩家执行命令 8=使该玩家发送消息 16=对该玩家发送消息 32=控制台显示警告信息 64=将警告信息保存至警告日志
    #以上处理方式不冲突，选择多种处理方式相加即可。例如 既要发送全服公告又要控制台执行命令 则1+2=3 处理方法填3即可。
    #默认1+2+32+64=99
    method: 99
    #以下为各处理方法的详细设置，使用{player}表示该玩家的名字，{command}表示事件命令。

    #要发送的公告 支持多条 按格式添加
    broadcast:
      - '§e[§d公告§e]§4玩家§a{player}§4因利用bug获取OP权限而惨遭封禁!'
      - '§e[§d公告§e]§4玩家§a{player}§4因利用bug获取OP权限而惨遭封禁!'
      - '§e[§d公告§e]§4玩家§a{player}§4因利用bug获取OP权限而惨遭封禁!'

    #控制台执行的命令 支持多个 按格式添加
    consoleCmd:
      - 'deop {player}'
      - 'ban {player}'

    #使该玩家执行的命令 支持多个 按格式添加
    #需注意本方法的优先级低于控制台执行命令，并且不能执行该玩家无权执行的命令。
    #(如果使用本方法，切记要把这里写的命令加入白名单或在上一步用控制台取消该玩家的OP，不然...)
    playerCmd:
      - '/suicide'

    #使该玩家发送消息 支持多条 按格式添加
    playerSendMsg:
      - '我卡bug了!我卡bug了!我卡bug了!'

    #对该玩家发送消息 支持多条 按格式添加
    sendMsgToPlayer:
      - '惊喜不惊喜？意外不意外？'

    #控制台显示警告信息 支持多条 按格式添加
    consoleWarning:
      - '§4§l------------------警告------------------'
      - '§4玩家§b{player}§4不在白名单并以OP身份执行命令：§6{command}'
      - '§e请立即查询该玩家指令记录并检查权限系统是否存在漏洞'
      - '§4§l------------------警告------------------'

    #将警告保存到警告日志 支持多行 按格式添加，但不建议多行
    warningLog:
      - '玩家{player}以管理员身份执行命令：{command}, 请立即查询该玩家命令记录并检查权限系统是否存在漏洞'
